{{- if eq .Values.deployScalingOnly.enabled "false"}}
{{- if eq .Values.redirect "false" }}
{{- if not .Values.cronjob }}
{{- if eq (default "no" .Values.canary.enabled) "yes" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "canaryName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    strategy.spinnaker.io/use-source-capacity: "true"
  labels:
    app: {{ template "name" . }}
    app.kubernetes.io/name: {{ template "name" . }}
    namespace: {{ .Release.Namespace }}
    version: canary
    env: {{ default "stage" .Values.appEnv }}
    chart: {{ .Chart.Name }}
    tags.datadoghq.com/env: {{ default "stage" .Values.appEnv }}
    tags.datadoghq.com/service: {{ template "canaryName" . }}
    tags.datadoghq.com/version: {{ .Values.canary.image.canary.tag | quote}}
    voyager/rightSize: {{ default "true" .Values.deployment.voyager.rightSize | quote }}
    {{- if eq .Values.deployment.voyager.rightSize "true" }}
    voyager/containersToRightSize: {{ default (printf "%s.%s" .Values.appName "fluentd-cloudwatch") .Values.deployment.voyager.containersToRightSize | quote }}
    {{- end }}
{{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 4 }}
{{- end }}
spec:
  revisionHistoryLimit: 10
  strategy:
    {{- if eq .Values.deployment.strategy "Recreate" }}
    type: Recreate
    {{- else }}
    rollingUpdate:
      maxSurge: {{ default "50%" .Values.deployment.maxSurge }}
      maxUnavailable: {{ default "30%" .Values.deployment.maxUnavailable }}
    type: RollingUpdate
    {{- end }}
  replicas: {{ default 1 (add1 (div (mul .Values.canary.weight.canary .Values.currentReplica) 100)) }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      namespace: {{ .Release.Namespace }}
      version: canary
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        namespace: {{ .Release.Namespace }}
        version: canary
        rollover: {{ default "false" .Values.deployment.rollover | quote }}
        tags.datadoghq.com/env: {{ default "stage" .Values.appEnv }}
        tags.datadoghq.com/service: {{ template "canaryName" . }}
        tags.datadoghq.com/version: {{ .Values.canary.image.canary.tag | quote}}
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: http
        traffic.sidecar.istio.io/includeOutboundIPRanges: {{ template "outboundIPInterception" . }}
{{- if .Values.deployment.podAnnotations }}
{{ toYaml .Values.deployment.podAnnotations | indent 8 }}
{{- end }}
    spec:
  {{- if eq (default "false" .Values.deployment.serviceAccount.enabled) "true" }}
    {{- if .Values.deployment.serviceAccount.name }}
      serviceAccountName: {{ .Values.deployment.serviceAccount.name }}
    {{- else }}
      serviceAccountName: {{ template "name" . }}-sa
    {{- end }} 
  {{- end }}
      volumes:
        - name: config
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-cloudwatch
            defaultMode: 420
        - name: applogs
          emptyDir: {}
    {{- if .Values.secretFiles }}
      {{- range $p := .Values.secretFiles }}
        - name: {{ .name }}
          secret:
            secretName: {{ template "name" $ }}-{{ .name }}
      {{- end }}
    {{- end }}
    {{- if eq .Values.deployment.dnsPolicy "None"}}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 10.100.0.10
        searches:
        - svc.cluster.local
        - cluster.local
        - ap-south-1.compute.internal
        - ap-south-1.amazonaws.com
        options:
        - name: ndots
          value: "2"
    {{- end }}
      initContainers:
      - name: copy-fluentd-config
        image: 035243212545.dkr.ecr.ap-south-1.amazonaws.com/curefit/busybox:latest
        command:
        - sh
        - "-c"
        - cp /config-volume/* /etc/fluentd
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: "/config-volume"
        - name: config
          mountPath: "/etc/fluentd"
        terminationMessagePath: "/dev/termination.log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
    {{- if .Values.deployment.initContainers }}
      {{- range $p := .Values.deployment.initContainers }}
      - name: {{ .name }}
        image: "{{ $.Values.deployment.image.repository }}:{{ $.Values.deployment.image.tag }}"
        command: {{ toJson (.command) }}
        resources: {}
        terminationMessagePath: "/dev/termination.log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ template "name" $ }}-env-config-map
        {{- if $.Values.secrets }}
        - secretRef:
            name: {{ template "name" $ }}
        {{- end }}
        {{- if $.Values.externalSecrets }}
        - secretRef:
            name: {{ template "name" $ }}-external
        {{- end }}
      {{- end }}
    {{- end }}
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.canary.image.canary.repository }}:{{ .Values.canary.image.canary.tag }}"
        lifecycle:                   
          preStop:                   
            exec:                    
              command:               
              - sh
              - -c
              - "{{ default "echo Done" .Values.deployment.preStopCommand}} && sleep {{ default 80 .Values.deployment.drainTime }}"
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: DD_VERSION
          value: {{ .Values.canary.image.canary.tag | quote }}
        envFrom:
        - configMapRef:
            name: {{ template "name" . }}-canary-env-config-map
        {{- if .Values.secrets }}
        - secretRef:
            name: {{ template "name" $ }}
        {{- end }}
        {{- if .Values.externalSecrets }}
        - secretRef:
            name: {{ template "name" $ }}-external
        {{- end }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        terminationMessagePath: "/logs/{{ default .Values.appName .Values.deployment.logDir }}/termination.log"
        terminationMessagePolicy: "FallbackToLogsOnError"
        volumeMounts:
        - name: applogs
          mountPath: /logs/{{ default .Values.appName .Values.deployment.logDir }}
        {{- if .Values.secretFiles }}
        {{- range $p := .Values.secretFiles }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          readOnly: true
        {{- end }}
        {{- end }}
        ports:
        {{- range $p := .Values.service.expose }}
        - containerPort: {{ . }}
        {{- end }}
        {{- if eq .Values.metrics.enabled true }}
        {{- if ne .Values.metrics.port (index .Values.service.expose 0) }}
        - containerPort: {{ .Values.metrics.port }}
        {{- end }}
        {{- end }}
        {{- if eq .Values.deployment.probe.type "tcp" }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.deployment.probe.probePort }}
          initialDelaySeconds: {{ default "30" .Values.deployment.probe.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "20" .Values.deployment.probe.livenessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.deployment.probe.livenessProbe.successThreshold }}
          timeoutSeconds: {{ default "1" .Values.deployment.probe.livenessProbe.timeoutSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.deployment.probe.probePort }}
          initialDelaySeconds: {{ default "30" .Values.deployment.probe.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "15" .Values.deployment.probe.readinessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.deployment.probe.livenessProbe.successThreshold }}
          timeoutSeconds: {{ default "1" .Values.deployment.probe.livenessProbe.timeoutSeconds }}
        {{- else if eq .Values.deployment.probe.type "exec" }}
        livenessProbe:
          exec:
            command: {{ toJson (.Values.deployment.probe.command) }}
          initialDelaySeconds: {{ default "30" .Values.deployment.probe.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "20" .Values.deployment.probe.livenessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.deployment.probe.livenessProbe.successThreshold }}
          timeoutSeconds: {{ default "1" .Values.deployment.probe.livenessProbe.timeoutSeconds }}
        readinessProbe:
          exec:
            command: {{ toJson (.Values.deployment.probe.command) }}
          initialDelaySeconds: {{ default "30" .Values.deployment.probe.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "15" .Values.deployment.probe.readinessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.deployment.probe.livenessProbe.successThreshold }}
          timeoutSeconds: {{ default "1" .Values.deployment.probe.livenessProbe.timeoutSeconds }}
        {{- else if eq .Values.deployment.probe.type "http" }}
        livenessProbe:
          httpGet:
            path: {{ default "/status" .Values.deployment.probePath }}
            port: {{ .Values.deployment.probePort }}
          initialDelaySeconds: {{ default "30" .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "20" .Values.deployment.livenessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.deployment.livenessProbe.successThreshold }}
          timeoutSeconds: {{ default "1" .Values.deployment.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ default "/status" .Values.deployment.probePath }}
            port: {{ .Values.deployment.probePort }}
          initialDelaySeconds: {{ default "30" .Values.deployment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "15" .Values.deployment.readinessProbe.periodSeconds }}
          successThreshold: {{ default "1"  .Values.deployment.readinessProbe.successThreshold }}
          timeoutSeconds: {{ default "1" .Values.deployment.readinessProbe.timeoutSeconds }}
        {{- end }}
        resources:
{{ toYaml .Values.deployment.resources | indent 12 }}
      - name: fluentd-cloudwatch
        image: 035243212545.dkr.ecr.ap-south-1.amazonaws.com/curefit/fluentd:coralogix-1.1.9
        lifecycle:                   
          preStop:                   
            exec:                    
              command:               
              - sh
              - -c
              - "sleep {{ default 110 .Values.drainTime }}"
        env:
        - name: AWS_REGION
          value: {{ default "ap-south-1" .Values.region }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: "/fluentd/etc"
        - name: applogs
          mountPath: /logs/{{ default .Values.appName .Values.deployment.logDir }}
          readOnly: true
        terminationMessagePath: "/dev/termination.log"
        terminationMessagePolicy: "FallbackToLogsOnError"
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: {{ default "300" .Values.deployment.terminationGracePeriodSeconds }}
      affinity:
        {{- if .Values.deployment.nodeAffinity }}
        nodeAffinity:
        {{- "\n"}}{{ toYaml .Values.deployment.nodeAffinity | indent 10}}
        {{- end }}
        {{- if .Values.deployment.podAntiAffinity }}
        podAntiAffinity:
        {{- "\n"}}{{ toYaml .Values.deployment.podAntiAffinity | indent 10}}
        {{- end }}
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "name" . }}
              topologyKey: "kubernetes.io/hostname"
    {{- with .Values.deployment.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}