{{- if eq .Values.deployScalingOnly.enabled "false"}}
{{- if .Values.externalSecrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "name" . }}-external
  namespace : {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::035243212545:role/k8s-external-secrets
  region: {{ default "ap-south-1" .Values.region }}
  dataFrom:
{{- $flag := "false" -}}
{{- range .Values.externalSecrets.names }}
  {{- $flag = "true" }}
    - {{ . }}
{{- end }}
{{- if eq $flag "false" }}
    - {{ template "secretName" . }}
{{- end }}
---
{{- end }}
{{- end }}