{{- if eq .Values.deployScalingOnly.enabled "false"}}
{{- if eq .Values.ingress.enabled true }}
{{ $ver :=  1 }}
{{- range $s := .Values.ingress.data }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" $ }}-{{ $ver }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "name" $ }}
    chart: {{ template "chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
{{ toYaml $s.annotations | indent 4 }}
spec:
  rules:
    {{- range $p := $s.config }}
    - host:  {{ $p.host }}
      http:
        paths:
          {{- range $q := .paths }}
          {{- range $r := .path }}
          - path: {{  . | quote}}
            backend:
              serviceName: {{ $q.service }}
              servicePort: {{ $q.port }}
          {{- end -}}
          {{- end -}}
        {{- end -}}
{{ $ver = add $ver 1 }}
{{- end -}}

{{- end -}}
{{- end }}