{{- if .Values.scaling }}
{{- if .Values.scaling.keda }} #applied only if keda configs present
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "name" . }}-keda-scaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ template "name" . }}
    envSourceContainerName: {{ template "name" . }}
  pollingInterval: {{ default "30" .Values.scaling.keda.pollingInterval}}
  cooldownPeriod:  {{ default "90" .Values.scaling.keda.cooldownPeriod}}
  {{- if eq .Values.scalingOverride.enabled "true" }}
  minReplicaCount: {{ default "1" .Values.scalingOverride.minReplicas}}
  maxReplicaCount: {{ default "1" .Values.scalingOverride.maxReplicas}}
  {{- else if .Values.scaling }}
  minReplicaCount: {{ default "1" .Values.scaling.minReplicas }}
  maxReplicaCount: {{ default "1" .Values.scaling.maxReplicas }}
  {{- end }}
  triggers:
  {{- "\n"}}{{ toYaml .Values.scaling.keda.triggers | indent 4}}
    - type: cpu
      metadata:
        type: Utilization
        {{- if eq .Values.scalingOverride.enabled "true" }}
        value: {{ default "80" .Values.scalingOverride.targetCPUUtilPercentage | quote}}
        {{- else if .Values.scaling }}
        value: {{ default "80" .Values.scaling.targetCPUUtilPercentage | quote}}
        {{- end }}
---
{{- end }}
{{- end }}
