deployment:
  labels:
    billing: eat
    sub-billing: graphhopper
  probePath: /route?point=12.980269%2C77.694232&point=12.979178%2C77.69725&type=json&locale=en-GB&vehicle=car&weighting=fastest&elevation=false
  probePort: 8989
  resources:
    limits:
      cpu: 2.5
      memory: 5500Mi
    requests:
      cpu: 1
      memory: 4000Mi
istio:
  internal:
    hosts:
    - graphhopper.production.eatfit.internal
    timeout: 360s
service:
  expose:
  - 8989
scalingOverride:
  enabled: "true"
  averageUtilization: 50
  minReplicas: 4
  maxReplicas: 100