deployment:
  labels:
    billing: eat
    sub-billing: graphhopper
  probePath: /route?point=12.980269%2C77.694232&point=12.979178%2C77.69725&type=json&locale=en-GB&vehicle=car&weighting=fastest&elevation=false
  probePort: 8989
  resources:
    limits:
      cpu: 2
      memory: 5000Mi
    requests:
      cpu: 1
      memory: 3500Mi
istio:
  internal:
    hosts:
      - graphhopper.stage.cure.fit.internal
  vpn:
    hosts:
      - graphhopper.stage.curefit.co
  mesh:
    timeout: 360s
service:
  expose:
  - 8989

scaling:
  scaleUpAtCPU: 0.5
  minReplicas: 1
  maxReplicas: 2
  keda:
    triggers:
      - type: cpu
        metadata:
          value: "550m"
        metricType: AverageValue # Allowed types are 'Utilization' or 'AverageValue'
      - type: cron # scale up from 8:40am-6:20pm
        metadata:
          timezone: Asia/Kolkata
          start: 40 8 * * *
          end: 20 18 * * *
          desiredReplicas: "1"
