deployment:
  labels:
    billing: eat
    sub-billing: graphhopper
  probePath: /route?point=12.980269%2C77.694232&point=12.979178%2C77.69725&type=json&locale=en-GB&vehicle=car&weighting=fastest&elevation=false
  probePort: 8989
  resources:
    limits:
      cpu: 200m
      memory: 2.5Gi
    requests:
      cpu: 100m
      memory: 2Gi
istio:
  internal:
    hosts:
      - graphhopper.stage.eatfit.internal
  vpn:
    hosts:
      - graphhopper.stage.eatfit.in
  mesh:
    timeout: 360s
service:
  expose:
  - 8989
scalingOverride:
  enabled: "true"
  averageUtilization: 90
  minReplicas: 1
  maxReplicas: 5