deployment:
  labels:
    billing: eat
    sub-billing: graphhopper
  probePath: /route?point=12.980269%2C77.694232&point=12.979178%2C77.69725&type=json&locale=en-GB&vehicle=car&weighting=fastest&elevation=false
  probePort: 8989
  resources:
    limits:
      cpu: 1.5
      memory: 4500Mi
    requests:
      cpu: 0.5
      memory: 3000Mi
istio:
  internal:
    hosts:
    - graphhopper.production.eatfit.internal
    timeout: 360s
service:
  expose:
  - 8989
