name: Submit Dependencies

on:
  push:
    branches:
      - master

jobs:
  submit-dependencies:
    uses: curefit/actions-template/.github/workflows/submit-dependencies.yaml@master
    with:
      java_version: 8
